### ISSUE TITLE
About Parameters

### ISSUE THREAD

**Issue by HyunsooCha** [philgras/video-head-tracker#1]
Hi, thank you for your excellent work!

I have some questions related to parameters. 

1. In a rigid pose, the rotation parameter's dimension is the torch.Size([1, 3]). What is the type of this rotation? I was confused that the type is radian angle (yaw, pitch, roll) or angle-axis.
2. In a translation, what is the unit of this parameter? Pixel or cm?
3. The camera intrinsic parameter yielded [0.31053847 0.50841707 0.5909382]. I guess the first one is focal length, and the other is cx, cy. However, when I used the MATLAB toolbox by CalTech, I got the focal length to 2463 as the same dataset. What is the type or unit of focal length on your code?

I'm so happy to know your excellent work! This code is really helpful to me. 

Thank you.

**Comment by philgras** [comment]
Hi!

1) Its axis-angle representation. The `batch_rodrigues` function in `vht/model/lbs.py` gets you the rotation matrix. 
2) The translation vector as well as vertex coordinates of FLAME are given in meters.
3) [f, cx, cy] is right. The values are normalized. To denormalize them for a resolution of `[h,w]`, do `f * max(h, w)` and `cx * w` and `cy * h`. These values are then in pixel units.

Hope this helps.

**Comment by HyunsooCha** [comment]
Thank you for your reply! It is beneficial to use the code.
