### ISSUE TITLE
About rotation and translation in the output

### ISSUE THREAD

**Issue by Nuyoah13** [philgras/video-head-tracker#4]
Hi,

Thanks for sharing this excellent code.
I want to know what do the rotation and translation represent respectively, where the size are [1, 3] for each frame. Can I transform them to the camera2world matrix?

**Comment by philgras** [comment]
Hi,

Thanks a lot for your interest in our work. For each frame, an axis-angle vector and a translation vector is optimized which represents the rigid transformation between the camera and the flame model. In our work, we assumed the camera to be static and only the flame head to move. So, world2cam is actually the identity. But you can interpret the rigid movements of the tracked head model as camera movements and compose a world2view matrix. To turn the axis-angle vector into a rotation matrix, look at the function batch_rodrigues in vht/model/lbs.py

Hope this helps!
